//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_App.Configs.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Res {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Res() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Web_App.Configs.Resource.Res", typeof(Res).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Accion {
            get {
                return ResourceManager.GetString("Accion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Acciones {
            get {
                return ResourceManager.GetString("Acciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Aceptar {
            get {
                return ResourceManager.GetString("Aceptar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ActivarDesactivar {
            get {
                return ResourceManager.GetString("ActivarDesactivar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string AdquirirMembresia {
            get {
                return ResourceManager.GetString("AdquirirMembresia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string AdquirirMembresiaPremium {
            get {
                return ResourceManager.GetString("AdquirirMembresiaPremium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Agrega {
            get {
                return ResourceManager.GetString("Agrega", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string AgregarHorasTrabajadasDescripcion {
            get {
                return ResourceManager.GetString("AgregarHorasTrabajadasDescripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string AgregarTrabajadorOferta {
            get {
                return ResourceManager.GetString("AgregarTrabajadorOferta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Annadir {
            get {
                return ResourceManager.GetString("Annadir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string AprobacionProveedores {
            get {
                return ResourceManager.GetString("AprobacionProveedores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Bitacora {
            get {
                return ResourceManager.GetString("Bitacora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string BitacoraDescripcion {
            get {
                return ResourceManager.GetString("BitacoraDescripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string BorrarMarca {
            get {
                return ResourceManager.GetString("BorrarMarca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Buscar {
            get {
                return ResourceManager.GetString("Buscar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Bye {
            get {
                return ResourceManager.GetString("Bye", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string CalificacionEmpresa {
            get {
                return ResourceManager.GetString("CalificacionEmpresa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string CalificacionTrabajador {
            get {
                return ResourceManager.GetString("CalificacionTrabajador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string CalificacionTrabajo {
            get {
                return ResourceManager.GetString("CalificacionTrabajo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string CambiarContrasenna {
            get {
                return ResourceManager.GetString("CambiarContrasenna", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Cancelar {
            get {
                return ResourceManager.GetString("Cancelar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string CancelarSolicitud {
            get {
                return ResourceManager.GetString("CancelarSolicitud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string CancelarSolicitudTrabajo {
            get {
                return ResourceManager.GetString("CancelarSolicitudTrabajo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Canton {
            get {
                return ResourceManager.GetString("Canton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Cedula {
            get {
                return ResourceManager.GetString("Cedula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string CedulaJuridica {
            get {
                return ResourceManager.GetString("CedulaJuridica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string CerrarSesion {
            get {
                return ResourceManager.GetString("CerrarSesion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string CodigoQR {
            get {
                return ResourceManager.GetString("CodigoQR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string CodigoQRInvalido {
            get {
                return ResourceManager.GetString("CodigoQRInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ComentarioEmpresa {
            get {
                return ResourceManager.GetString("ComentarioEmpresa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ComentariorTrabajo {
            get {
                return ResourceManager.GetString("ComentariorTrabajo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ComentarioTrabajador {
            get {
                return ResourceManager.GetString("ComentarioTrabajador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ComenzarATrabajarEnSusProyectos {
            get {
                return ResourceManager.GetString("ComenzarATrabajarEnSusProyectos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ComienceAAprender {
            get {
                return ResourceManager.GetString("ComienceAAprender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ComienceAConstruir {
            get {
                return ResourceManager.GetString("ComienceAConstruir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ComienceADisenar {
            get {
                return ResourceManager.GetString("ComienceADisenar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ComprarAhora {
            get {
                return ResourceManager.GetString("ComprarAhora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Confianza {
            get {
                return ResourceManager.GetString("Confianza", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ConfianzaDescripcion {
            get {
                return ResourceManager.GetString("ConfianzaDescripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Configuraciones {
            get {
                return ResourceManager.GetString("Configuraciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ConfiguracionesDescripcion {
            get {
                return ResourceManager.GetString("ConfiguracionesDescripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ConfirmacionCancelacionSolicitud {
            get {
                return ResourceManager.GetString("ConfirmacionCancelacionSolicitud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ConfirmacionEliminar {
            get {
                return ResourceManager.GetString("ConfirmacionEliminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ConfirmacionEstado {
            get {
                return ResourceManager.GetString("ConfirmacionEstado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ConfirmarContrasenna {
            get {
                return ResourceManager.GetString("ConfirmarContrasenna", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ConfirmarMembresiaEstandar {
            get {
                return ResourceManager.GetString("ConfirmarMembresiaEstandar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ConfirmarMembresiaEstandarTexto1 {
            get {
                return ResourceManager.GetString("ConfirmarMembresiaEstandarTexto1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ConfirmarMembresiaEstandarTexto2 {
            get {
                return ResourceManager.GetString("ConfirmarMembresiaEstandarTexto2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Conocenos {
            get {
                return ResourceManager.GetString("Conocenos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ConozcaMaster {
            get {
                return ResourceManager.GetString("ConozcaMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ContacteALosMejores {
            get {
                return ResourceManager.GetString("ContacteALosMejores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Continuar {
            get {
                return ResourceManager.GetString("Continuar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Contrasenna {
            get {
                return ResourceManager.GetString("Contrasenna", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ConvertirseEnMaster {
            get {
                return ResourceManager.GetString("ConvertirseEnMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ConvertirseEnMasterPremium {
            get {
                return ResourceManager.GetString("ConvertirseEnMasterPremium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string CorreoElectronico {
            get {
                return ResourceManager.GetString("CorreoElectronico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string CostoNeto {
            get {
                return ResourceManager.GetString("CostoNeto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Crear {
            get {
                return ResourceManager.GetString("Crear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string CumpleConElFormato {
            get {
                return ResourceManager.GetString("CumpleConElFormato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Descripcion {
            get {
                return ResourceManager.GetString("Descripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string DescripcionMasterLanding {
            get {
                return ResourceManager.GetString("DescripcionMasterLanding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string DeseaAgregarPresupuesto {
            get {
                return ResourceManager.GetString("DeseaAgregarPresupuesto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string DetallesOfertaTrabajo {
            get {
                return ResourceManager.GetString("DetallesOfertaTrabajo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string DetallesOfertaTrabajoDescripcion {
            get {
                return ResourceManager.GetString("DetallesOfertaTrabajoDescripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string DireccionExacta {
            get {
                return ResourceManager.GetString("DireccionExacta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Distrito {
            get {
                return ResourceManager.GetString("Distrito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Documentos {
            get {
                return ResourceManager.GetString("Documentos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string DocumentosDescripcion {
            get {
                return ResourceManager.GetString("DocumentosDescripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string EdicionPerfilAdministrador {
            get {
                return ResourceManager.GetString("EdicionPerfilAdministrador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Editar {
            get {
                return ResourceManager.GetString("Editar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string EditarPerfil {
            get {
                return ResourceManager.GetString("EditarPerfil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ElaboradoPor {
            get {
                return ResourceManager.GetString("ElaboradoPor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Eliminar {
            get {
                return ResourceManager.GetString("Eliminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string EliminarTrabajadoresOferta {
            get {
                return ResourceManager.GetString("EliminarTrabajadoresOferta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string EncontrarMejoresProfesionales {
            get {
                return ResourceManager.GetString("EncontrarMejoresProfesionales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Entidad {
            get {
                return ResourceManager.GetString("Entidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Especialidades {
            get {
                return ResourceManager.GetString("Especialidades", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Estadisticas {
            get {
                return ResourceManager.GetString("Estadisticas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Estado {
            get {
                return ResourceManager.GetString("Estado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Expertos {
            get {
                return ResourceManager.GetString("Expertos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ExpertosDescripcion {
            get {
                return ResourceManager.GetString("ExpertosDescripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ExtenderMembresia {
            get {
                return ResourceManager.GetString("ExtenderMembresia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ExtenderMembresiaPremium {
            get {
                return ResourceManager.GetString("ExtenderMembresiaPremium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Fecha {
            get {
                return ResourceManager.GetString("Fecha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string FechaCreacion {
            get {
                return ResourceManager.GetString("FechaCreacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string FechaInicioTrabajo {
            get {
                return ResourceManager.GetString("FechaInicioTrabajo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string FechaNacimiento {
            get {
                return ResourceManager.GetString("FechaNacimiento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string FinalizarSolicitudAgregarFotografias {
            get {
                return ResourceManager.GetString("FinalizarSolicitudAgregarFotografias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string FinalizarSolicitudTrabajo {
            get {
                return ResourceManager.GetString("FinalizarSolicitudTrabajo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string FinalizarSolicitudTrabajoDescripcion {
            get {
                return ResourceManager.GetString("FinalizarSolicitudTrabajoDescripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Fotografias {
            get {
                return ResourceManager.GetString("Fotografias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string GenerarNuevaSolicitudTrabajo {
            get {
                return ResourceManager.GetString("GenerarNuevaSolicitudTrabajo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string GenerarNuevaSolicitudTrabajoDescripcion {
            get {
                return ResourceManager.GetString("GenerarNuevaSolicitudTrabajoDescripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Genero {
            get {
                return ResourceManager.GetString("Genero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string GraciasPorConfiarEnMaster {
            get {
                return ResourceManager.GetString("GraciasPorConfiarEnMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Guardar {
            get {
                return ResourceManager.GetString("Guardar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string HacerOferta {
            get {
                return ResourceManager.GetString("HacerOferta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Hola {
            get {
                return ResourceManager.GetString("Hola", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ID {
            get {
                return ResourceManager.GetString("ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Identificacion {
            get {
                return ResourceManager.GetString("Identificacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Identificador {
            get {
                return ResourceManager.GetString("Identificador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string IDPropietario {
            get {
                return ResourceManager.GetString("IDPropietario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string IDUsuario {
            get {
                return ResourceManager.GetString("IDUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ImpulsarNegocio {
            get {
                return ResourceManager.GetString("ImpulsarNegocio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ImpulsarNegocioPremium {
            get {
                return ResourceManager.GetString("ImpulsarNegocioPremium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string IngresarTextoCrear {
            get {
                return ResourceManager.GetString("IngresarTextoCrear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string IngresarTextoEditar {
            get {
                return ResourceManager.GetString("IngresarTextoEditar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string IngresosDiarios {
            get {
                return ResourceManager.GetString("IngresosDiarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string IngresoSeisMesesDescripcion {
            get {
                return ResourceManager.GetString("IngresoSeisMesesDescripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string IngresosSeisMeses {
            get {
                return ResourceManager.GetString("IngresosSeisMeses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string IniciarSesion {
            get {
                return ResourceManager.GetString("IniciarSesion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string IniciarSolicitudTrabajo {
            get {
                return ResourceManager.GetString("IniciarSolicitudTrabajo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string IniciarSolicitudTrabajoDescripcion {
            get {
                return ResourceManager.GetString("IniciarSolicitudTrabajoDescripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Inicio {
            get {
                return ResourceManager.GetString("Inicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string InicioSesion {
            get {
                return ResourceManager.GetString("InicioSesion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string InscripcionAnual {
            get {
                return ResourceManager.GetString("InscripcionAnual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string InscripcionAnualDescripcion {
            get {
                return ResourceManager.GetString("InscripcionAnualDescripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string IrAhora {
            get {
                return ResourceManager.GetString("IrAhora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string IVA {
            get {
                return ResourceManager.GetString("IVA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string LenguajeDelSistema {
            get {
                return ResourceManager.GetString("LenguajeDelSistema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Licencias {
            get {
                return ResourceManager.GetString("Licencias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string LicenciasDescripcion {
            get {
                return ResourceManager.GetString("LicenciasDescripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ListarSolicitudesDescripcion {
            get {
                return ResourceManager.GetString("ListarSolicitudesDescripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ListaUsuarios {
            get {
                return ResourceManager.GetString("ListaUsuarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Listo {
            get {
                return ResourceManager.GetString("Listo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MantenimientoEspecialidadDescripcion {
            get {
                return ResourceManager.GetString("MantenimientoEspecialidadDescripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MantenimientoTiposTrabajoDescripcion {
            get {
                return ResourceManager.GetString("MantenimientoTiposTrabajoDescripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MejorarMembresia {
            get {
                return ResourceManager.GetString("MejorarMembresia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Membresia {
            get {
                return ResourceManager.GetString("Membresia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MembresiaEstandar {
            get {
                return ResourceManager.GetString("MembresiaEstandar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MembresiaEstandarDescripcion {
            get {
                return ResourceManager.GetString("MembresiaEstandarDescripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MembresiaPremium {
            get {
                return ResourceManager.GetString("MembresiaPremium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MembresiaPremiumDescripcion {
            get {
                return ResourceManager.GetString("MembresiaPremiumDescripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Membresias {
            get {
                return ResourceManager.GetString("Membresias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MembresiasDescripcion {
            get {
                return ResourceManager.GetString("MembresiasDescripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MonedaParaUsarEnElSistema {
            get {
                return ResourceManager.GetString("MonedaParaUsarEnElSistema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string NoCumpleConElFormato {
            get {
                return ResourceManager.GetString("NoCumpleConElFormato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Nombre {
            get {
                return ResourceManager.GetString("Nombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string NombreComercial {
            get {
                return ResourceManager.GetString("NombreComercial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string NombreEmpresa {
            get {
                return ResourceManager.GetString("NombreEmpresa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string OferentesPendientes {
            get {
                return ResourceManager.GetString("OferentesPendientes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string OfertaRealizadaDurante {
            get {
                return ResourceManager.GetString("OfertaRealizadaDurante", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string OfertaRealizadaPor {
            get {
                return ResourceManager.GetString("OfertaRealizadaPor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string OfertasTrabajo {
            get {
                return ResourceManager.GetString("OfertasTrabajo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string OfertasTrabajoDescripcion {
            get {
                return ResourceManager.GetString("OfertasTrabajoDescripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string OfertaTrabajoAceptada {
            get {
                return ResourceManager.GetString("OfertaTrabajoAceptada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string OfertaTrabajoAceptadaDescripcion {
            get {
                return ResourceManager.GetString("OfertaTrabajoAceptadaDescripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string OlvidarContrasenna {
            get {
                return ResourceManager.GetString("OlvidarContrasenna", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string OlvidoSuContrasennaPregunta {
            get {
                return ResourceManager.GetString("OlvidoSuContrasennaPregunta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string OpcionAgregarPresupuesto {
            get {
                return ResourceManager.GetString("OpcionAgregarPresupuesto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string PaisDeNacimiento {
            get {
                return ResourceManager.GetString("PaisDeNacimiento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string PanelControl {
            get {
                return ResourceManager.GetString("PanelControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string PanelControlDescripcion {
            get {
                return ResourceManager.GetString("PanelControlDescripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Pasaporte {
            get {
                return ResourceManager.GetString("Pasaporte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Perfil {
            get {
                return ResourceManager.GetString("Perfil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string PerfilAdministrador {
            get {
                return ResourceManager.GetString("PerfilAdministrador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string PorcentajeComisionPorTrabajo {
            get {
                return ResourceManager.GetString("PorcentajeComisionPorTrabajo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Precio {
            get {
                return ResourceManager.GetString("Precio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string PrecioCancelacion {
            get {
                return ResourceManager.GetString("PrecioCancelacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Presupuesto {
            get {
                return ResourceManager.GetString("Presupuesto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string PrimerApellido {
            get {
                return ResourceManager.GetString("PrimerApellido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Productos {
            get {
                return ResourceManager.GetString("Productos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string PromocioneSuTrabajo {
            get {
                return ResourceManager.GetString("PromocioneSuTrabajo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string PromocioneSuTrabajoDescripcion {
            get {
                return ResourceManager.GetString("PromocioneSuTrabajoDescripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Provincia {
            get {
                return ResourceManager.GetString("Provincia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string RazonSocial {
            get {
                return ResourceManager.GetString("RazonSocial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string RealizarPagoSolicitud {
            get {
                return ResourceManager.GetString("RealizarPagoSolicitud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string RealizarPagoSolicitudDescripcion {
            get {
                return ResourceManager.GetString("RealizarPagoSolicitudDescripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string RealizarPagoSolicitudPaypal {
            get {
                return ResourceManager.GetString("RealizarPagoSolicitudPaypal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Rechazar {
            get {
                return ResourceManager.GetString("Rechazar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string RechazarOfertaTrabajo {
            get {
                return ResourceManager.GetString("RechazarOfertaTrabajo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string RechazarOfertaTrabajoDescripcion {
            get {
                return ResourceManager.GetString("RechazarOfertaTrabajoDescripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string RecibaSusGanancias {
            get {
                return ResourceManager.GetString("RecibaSusGanancias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string RecibaSusGananciasDescripcion {
            get {
                return ResourceManager.GetString("RecibaSusGananciasDescripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string RegistrarAdministrador {
            get {
                return ResourceManager.GetString("RegistrarAdministrador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string RegistrarCliente {
            get {
                return ResourceManager.GetString("RegistrarCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string RegistrarOferenteFisico {
            get {
                return ResourceManager.GetString("RegistrarOferenteFisico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string RegistrarOferenteJuridico {
            get {
                return ResourceManager.GetString("RegistrarOferenteJuridico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string RegistrarTrabajador {
            get {
                return ResourceManager.GetString("RegistrarTrabajador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string RegistreseAhora {
            get {
                return ResourceManager.GetString("RegistreseAhora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string RegistreseSinNingunCostoAdicional {
            get {
                return ResourceManager.GetString("RegistreseSinNingunCostoAdicional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string RegresarListaOfertas {
            get {
                return ResourceManager.GetString("RegresarListaOfertas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Residente {
            get {
                return ResourceManager.GetString("Residente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Rol {
            get {
                return ResourceManager.GetString("Rol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string RolDescripcion {
            get {
                return ResourceManager.GetString("RolDescripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Roles {
            get {
                return ResourceManager.GetString("Roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Saludo {
            get {
                return ResourceManager.GetString("Saludo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string SeaUnMaster {
            get {
                return ResourceManager.GetString("SeaUnMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string SegundoApellido {
            get {
                return ResourceManager.GetString("SegundoApellido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Seguridad {
            get {
                return ResourceManager.GetString("Seguridad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string SeguridadDescripcion {
            get {
                return ResourceManager.GetString("SeguridadDescripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string SeleccioneUnaOpcion {
            get {
                return ResourceManager.GetString("SeleccioneUnaOpcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Sistema {
            get {
                return ResourceManager.GetString("Sistema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string SolicitarCodigoQR {
            get {
                return ResourceManager.GetString("SolicitarCodigoQR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Solicitudes {
            get {
                return ResourceManager.GetString("Solicitudes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string SolicitudesActivas {
            get {
                return ResourceManager.GetString("SolicitudesActivas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string SolicitudesActivasDescripcion {
            get {
                return ResourceManager.GetString("SolicitudesActivasDescripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string SolicitudesCompletas {
            get {
                return ResourceManager.GetString("SolicitudesCompletas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string SolicitudesCompletasDescripcion {
            get {
                return ResourceManager.GetString("SolicitudesCompletasDescripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string SolicitudesPendientesAdjudicar {
            get {
                return ResourceManager.GetString("SolicitudesPendientesAdjudicar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string SolicitudesPendientesAdjudicarDescripcion {
            get {
                return ResourceManager.GetString("SolicitudesPendientesAdjudicarDescripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string SolicitudesPendientesCalificar {
            get {
                return ResourceManager.GetString("SolicitudesPendientesCalificar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string SolicitudesPendientesCalificarDescripcion {
            get {
                return ResourceManager.GetString("SolicitudesPendientesCalificarDescripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string SolicitudesPorIniciar {
            get {
                return ResourceManager.GetString("SolicitudesPorIniciar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string SolicitudesTrabajo {
            get {
                return ResourceManager.GetString("SolicitudesTrabajo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string SolicitudTrabajoEnviada {
            get {
                return ResourceManager.GetString("SolicitudTrabajoEnviada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string SolicitudTrabajoEnviadaDescripcion {
            get {
                return ResourceManager.GetString("SolicitudTrabajoEnviadaDescripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string SolicitudTrabajoFinalizada {
            get {
                return ResourceManager.GetString("SolicitudTrabajoFinalizada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string SolicitudTrabajoFinalizadaDescripcion {
            get {
                return ResourceManager.GetString("SolicitudTrabajoFinalizadaDescripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string SolicitudTrabajoIniciada {
            get {
                return ResourceManager.GetString("SolicitudTrabajoIniciada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string SolicitudTrabajoIniciadaDescripcion {
            get {
                return ResourceManager.GetString("SolicitudTrabajoIniciadaDescripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string SubirDocumento {
            get {
                return ResourceManager.GetString("SubirDocumento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string SubirFotografia {
            get {
                return ResourceManager.GetString("SubirFotografia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Telefono {
            get {
                return ResourceManager.GetString("Telefono", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string TerminosServicio {
            get {
                return ResourceManager.GetString("TerminosServicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string TieneEmpresa {
            get {
                return ResourceManager.GetString("TieneEmpresa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Tipo {
            get {
                return ResourceManager.GetString("Tipo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string TipoPago {
            get {
                return ResourceManager.GetString("TipoPago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string TiposTrabajo {
            get {
                return ResourceManager.GetString("TiposTrabajo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Titulo {
            get {
                return ResourceManager.GetString("Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string TotalDolares {
            get {
                return ResourceManager.GetString("TotalDolares", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Trabajadores {
            get {
                return ResourceManager.GetString("Trabajadores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string TrabajeConExpertos {
            get {
                return ResourceManager.GetString("TrabajeConExpertos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Trabajos {
            get {
                return ResourceManager.GetString("Trabajos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string URL {
            get {
                return ResourceManager.GetString("URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Usuario {
            get {
                return ResourceManager.GetString("Usuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Usuarios {
            get {
                return ResourceManager.GetString("Usuarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string VerboHTTP {
            get {
                return ResourceManager.GetString("VerboHTTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string VolverIntentar {
            get {
                return ResourceManager.GetString("VolverIntentar", resourceCulture);
            }
        }
    }
}
