
// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

namespace Web_App.AppCode.Helper.Language
{
    public static partial class LanguageHelper
    {
        public static string Accion
        {
            get { return GetString("Accion"); }
        }
   
        public static string Acciones
        {
            get { return GetString("Acciones"); }
        }
   
        public static string Aceptar
        {
            get { return GetString("Aceptar"); }
        }
   
        public static string ActivarDesactivar
        {
            get { return GetString("ActivarDesactivar"); }
        }
   
        public static string AdquirirMembresia
        {
            get { return GetString("AdquirirMembresia"); }
        }
   
        public static string AdquirirMembresiaPremium
        {
            get { return GetString("AdquirirMembresiaPremium"); }
        }
   
        public static string Agrega
        {
            get { return GetString("Agrega"); }
        }
   
        public static string AgregarHorasTrabajadasDescripcion
        {
            get { return GetString("AgregarHorasTrabajadasDescripcion"); }
        }
   
        public static string AgregarTrabajadorOferta
        {
            get { return GetString("AgregarTrabajadorOferta"); }
        }
   
        public static string Annadir
        {
            get { return GetString("Annadir"); }
        }
   
        public static string AprobacionProveedores
        {
            get { return GetString("AprobacionProveedores"); }
        }
   
        public static string Bitacora
        {
            get { return GetString("Bitacora"); }
        }
   
        public static string BitacoraDescripcion
        {
            get { return GetString("BitacoraDescripcion"); }
        }
   
        public static string BorrarMarca
        {
            get { return GetString("BorrarMarca"); }
        }
   
        public static string Buscar
        {
            get { return GetString("Buscar"); }
        }
   
        public static string Bye
        {
            get { return GetString("Bye"); }
        }
   
        public static string CalificacionEmpresa
        {
            get { return GetString("CalificacionEmpresa"); }
        }
   
        public static string CalificacionTrabajador
        {
            get { return GetString("CalificacionTrabajador"); }
        }
   
        public static string CalificacionTrabajo
        {
            get { return GetString("CalificacionTrabajo"); }
        }
   
        public static string CambiarContrasenna
        {
            get { return GetString("CambiarContrasenna"); }
        }
   
        public static string Cancelar
        {
            get { return GetString("Cancelar"); }
        }
   
        public static string CancelarSolicitud
        {
            get { return GetString("CancelarSolicitud"); }
        }
   
        public static string CancelarSolicitudTrabajo
        {
            get { return GetString("CancelarSolicitudTrabajo"); }
        }
   
        public static string Canton
        {
            get { return GetString("Canton"); }
        }
   
        public static string Cedula
        {
            get { return GetString("Cedula"); }
        }
   
        public static string CedulaJuridica
        {
            get { return GetString("CedulaJuridica"); }
        }
   
        public static string CerrarSesion
        {
            get { return GetString("CerrarSesion"); }
        }
   
        public static string CodigoQR
        {
            get { return GetString("CodigoQR"); }
        }
   
        public static string CodigoQRInvalido
        {
            get { return GetString("CodigoQRInvalido"); }
        }
   
        public static string ComentarioEmpresa
        {
            get { return GetString("ComentarioEmpresa"); }
        }
   
        public static string ComentariorTrabajo
        {
            get { return GetString("ComentariorTrabajo"); }
        }
   
        public static string ComentarioTrabajador
        {
            get { return GetString("ComentarioTrabajador"); }
        }
   
        public static string ComenzarATrabajarEnSusProyectos
        {
            get { return GetString("ComenzarATrabajarEnSusProyectos"); }
        }
   
        public static string ComienceAAprender
        {
            get { return GetString("ComienceAAprender"); }
        }
   
        public static string ComienceAConstruir
        {
            get { return GetString("ComienceAConstruir"); }
        }
   
        public static string ComienceADisenar
        {
            get { return GetString("ComienceADisenar"); }
        }
   
        public static string ComprarAhora
        {
            get { return GetString("ComprarAhora"); }
        }
   
        public static string Confianza
        {
            get { return GetString("Confianza"); }
        }
   
        public static string ConfianzaDescripcion
        {
            get { return GetString("ConfianzaDescripcion"); }
        }
   
        public static string Configuraciones
        {
            get { return GetString("Configuraciones"); }
        }
   
        public static string ConfiguracionesDescripcion
        {
            get { return GetString("ConfiguracionesDescripcion"); }
        }
   
        public static string ConfirmacionCancelacionSolicitud
        {
            get { return GetString("ConfirmacionCancelacionSolicitud"); }
        }
   
        public static string ConfirmacionEliminar
        {
            get { return GetString("ConfirmacionEliminar"); }
        }
   
        public static string ConfirmacionEstado
        {
            get { return GetString("ConfirmacionEstado"); }
        }
   
        public static string ConfirmarContrasenna
        {
            get { return GetString("ConfirmarContrasenna"); }
        }
   
        public static string ConfirmarMembresiaEstandar
        {
            get { return GetString("ConfirmarMembresiaEstandar"); }
        }
   
        public static string ConfirmarMembresiaEstandarTexto1
        {
            get { return GetString("ConfirmarMembresiaEstandarTexto1"); }
        }
   
        public static string ConfirmarMembresiaEstandarTexto2
        {
            get { return GetString("ConfirmarMembresiaEstandarTexto2"); }
        }
   
        public static string Conocenos
        {
            get { return GetString("Conocenos"); }
        }
   
        public static string ConozcaMaster
        {
            get { return GetString("ConozcaMaster"); }
        }
   
        public static string ContacteALosMejores
        {
            get { return GetString("ContacteALosMejores"); }
        }
   
        public static string Continuar
        {
            get { return GetString("Continuar"); }
        }
   
        public static string Contrasenna
        {
            get { return GetString("Contrasenna"); }
        }
   
        public static string ConvertirseEnMaster
        {
            get { return GetString("ConvertirseEnMaster"); }
        }
   
        public static string ConvertirseEnMasterPremium
        {
            get { return GetString("ConvertirseEnMasterPremium"); }
        }
   
        public static string CorreoElectronico
        {
            get { return GetString("CorreoElectronico"); }
        }
   
        public static string CostoNeto
        {
            get { return GetString("CostoNeto"); }
        }
   
        public static string Crear
        {
            get { return GetString("Crear"); }
        }
   
        public static string CumpleConElFormato
        {
            get { return GetString("CumpleConElFormato"); }
        }
   
        public static string Descripcion
        {
            get { return GetString("Descripcion"); }
        }
   
        public static string DescripcionMasterLanding
        {
            get { return GetString("DescripcionMasterLanding"); }
        }
   
        public static string DeseaAgregarPresupuesto
        {
            get { return GetString("DeseaAgregarPresupuesto"); }
        }
   
        public static string DetallesOfertaTrabajo
        {
            get { return GetString("DetallesOfertaTrabajo"); }
        }
   
        public static string DetallesOfertaTrabajoDescripcion
        {
            get { return GetString("DetallesOfertaTrabajoDescripcion"); }
        }
   
        public static string DireccionExacta
        {
            get { return GetString("DireccionExacta"); }
        }
   
        public static string Distrito
        {
            get { return GetString("Distrito"); }
        }
   
        public static string Documentos
        {
            get { return GetString("Documentos"); }
        }
   
        public static string DocumentosDescripcion
        {
            get { return GetString("DocumentosDescripcion"); }
        }
   
        public static string EdicionPerfilAdministrador
        {
            get { return GetString("EdicionPerfilAdministrador"); }
        }
   
        public static string Editar
        {
            get { return GetString("Editar"); }
        }
   
        public static string EditarPerfil
        {
            get { return GetString("EditarPerfil"); }
        }
   
        public static string ElaboradoPor
        {
            get { return GetString("ElaboradoPor"); }
        }
   
        public static string Eliminar
        {
            get { return GetString("Eliminar"); }
        }
   
        public static string EliminarTrabajadoresOferta
        {
            get { return GetString("EliminarTrabajadoresOferta"); }
        }
   
        public static string EncontrarMejoresProfesionales
        {
            get { return GetString("EncontrarMejoresProfesionales"); }
        }
   
        public static string Entidad
        {
            get { return GetString("Entidad"); }
        }
   
        public static string Especialidades
        {
            get { return GetString("Especialidades"); }
        }
   
        public static string Estadisticas
        {
            get { return GetString("Estadisticas"); }
        }
   
        public static string Estado
        {
            get { return GetString("Estado"); }
        }
   
        public static string Expertos
        {
            get { return GetString("Expertos"); }
        }
   
        public static string ExpertosDescripcion
        {
            get { return GetString("ExpertosDescripcion"); }
        }
   
        public static string ExtenderMembresia
        {
            get { return GetString("ExtenderMembresia"); }
        }
   
        public static string ExtenderMembresiaPremium
        {
            get { return GetString("ExtenderMembresiaPremium"); }
        }
   
        public static string Fecha
        {
            get { return GetString("Fecha"); }
        }
   
        public static string FechaCreacion
        {
            get { return GetString("FechaCreacion"); }
        }
   
        public static string FechaInicioTrabajo
        {
            get { return GetString("FechaInicioTrabajo"); }
        }
   
        public static string FechaNacimiento
        {
            get { return GetString("FechaNacimiento"); }
        }
   
        public static string FinalizarSolicitudAgregarFotografias
        {
            get { return GetString("FinalizarSolicitudAgregarFotografias"); }
        }
   
        public static string FinalizarSolicitudTrabajo
        {
            get { return GetString("FinalizarSolicitudTrabajo"); }
        }
   
        public static string FinalizarSolicitudTrabajoDescripcion
        {
            get { return GetString("FinalizarSolicitudTrabajoDescripcion"); }
        }
   
        public static string Fotografias
        {
            get { return GetString("Fotografias"); }
        }
   
        public static string GenerarNuevaSolicitudTrabajo
        {
            get { return GetString("GenerarNuevaSolicitudTrabajo"); }
        }
   
        public static string GenerarNuevaSolicitudTrabajoDescripcion
        {
            get { return GetString("GenerarNuevaSolicitudTrabajoDescripcion"); }
        }
   
        public static string Genero
        {
            get { return GetString("Genero"); }
        }
   
        public static string GraciasPorConfiarEnMaster
        {
            get { return GetString("GraciasPorConfiarEnMaster"); }
        }
   
        public static string Guardar
        {
            get { return GetString("Guardar"); }
        }
   
        public static string HacerOferta
        {
            get { return GetString("HacerOferta"); }
        }
   
        public static string Hola
        {
            get { return GetString("Hola"); }
        }
   
        public static string ID
        {
            get { return GetString("ID"); }
        }
   
        public static string Identificacion
        {
            get { return GetString("Identificacion"); }
        }
   
        public static string Identificador
        {
            get { return GetString("Identificador"); }
        }
   
        public static string IDPropietario
        {
            get { return GetString("IDPropietario"); }
        }
   
        public static string IDUsuario
        {
            get { return GetString("IDUsuario"); }
        }
   
        public static string ImpulsarNegocio
        {
            get { return GetString("ImpulsarNegocio"); }
        }
   
        public static string ImpulsarNegocioPremium
        {
            get { return GetString("ImpulsarNegocioPremium"); }
        }
   
        public static string IngresarTextoCrear
        {
            get { return GetString("IngresarTextoCrear"); }
        }
   
        public static string IngresarTextoEditar
        {
            get { return GetString("IngresarTextoEditar"); }
        }
   
        public static string IngresosDiarios
        {
            get { return GetString("IngresosDiarios"); }
        }
   
        public static string IngresoSeisMesesDescripcion
        {
            get { return GetString("IngresoSeisMesesDescripcion"); }
        }
   
        public static string IngresosSeisMeses
        {
            get { return GetString("IngresosSeisMeses"); }
        }
   
        public static string IniciarSesion
        {
            get { return GetString("IniciarSesion"); }
        }
   
        public static string IniciarSolicitudTrabajo
        {
            get { return GetString("IniciarSolicitudTrabajo"); }
        }
   
        public static string IniciarSolicitudTrabajoDescripcion
        {
            get { return GetString("IniciarSolicitudTrabajoDescripcion"); }
        }
   
        public static string Inicio
        {
            get { return GetString("Inicio"); }
        }
   
        public static string InicioSesion
        {
            get { return GetString("InicioSesion"); }
        }
   
        public static string InscripcionAnual
        {
            get { return GetString("InscripcionAnual"); }
        }
   
        public static string InscripcionAnualDescripcion
        {
            get { return GetString("InscripcionAnualDescripcion"); }
        }
   
        public static string IrAhora
        {
            get { return GetString("IrAhora"); }
        }
   
        public static string IVA
        {
            get { return GetString("IVA"); }
        }
   
        public static string LenguajeDelSistema
        {
            get { return GetString("LenguajeDelSistema"); }
        }
   
        public static string Licencias
        {
            get { return GetString("Licencias"); }
        }
   
        public static string LicenciasDescripcion
        {
            get { return GetString("LicenciasDescripcion"); }
        }
   
        public static string ListarSolicitudesDescripcion
        {
            get { return GetString("ListarSolicitudesDescripcion"); }
        }
   
        public static string ListaUsuarios
        {
            get { return GetString("ListaUsuarios"); }
        }
   
        public static string Listo
        {
            get { return GetString("Listo"); }
        }
   
        public static string MantenimientoEspecialidadDescripcion
        {
            get { return GetString("MantenimientoEspecialidadDescripcion"); }
        }
   
        public static string MantenimientoTiposTrabajoDescripcion
        {
            get { return GetString("MantenimientoTiposTrabajoDescripcion"); }
        }
   
        public static string MejorarMembresia
        {
            get { return GetString("MejorarMembresia"); }
        }
   
        public static string Membresia
        {
            get { return GetString("Membresia"); }
        }
   
        public static string MembresiaEstandar
        {
            get { return GetString("MembresiaEstandar"); }
        }
   
        public static string MembresiaEstandarDescripcion
        {
            get { return GetString("MembresiaEstandarDescripcion"); }
        }
   
        public static string MembresiaPremium
        {
            get { return GetString("MembresiaPremium"); }
        }
   
        public static string MembresiaPremiumDescripcion
        {
            get { return GetString("MembresiaPremiumDescripcion"); }
        }
   
        public static string Membresias
        {
            get { return GetString("Membresias"); }
        }
   
        public static string MembresiasDescripcion
        {
            get { return GetString("MembresiasDescripcion"); }
        }
   
        public static string MonedaParaUsarEnElSistema
        {
            get { return GetString("MonedaParaUsarEnElSistema"); }
        }
   
        public static string NoCumpleConElFormato
        {
            get { return GetString("NoCumpleConElFormato"); }
        }
   
        public static string Nombre
        {
            get { return GetString("Nombre"); }
        }
   
        public static string NombreComercial
        {
            get { return GetString("NombreComercial"); }
        }
   
        public static string NombreEmpresa
        {
            get { return GetString("NombreEmpresa"); }
        }
   
        public static string OferentesPendientes
        {
            get { return GetString("OferentesPendientes"); }
        }
   
        public static string OfertaRealizadaDurante
        {
            get { return GetString("OfertaRealizadaDurante"); }
        }
   
        public static string OfertaRealizadaPor
        {
            get { return GetString("OfertaRealizadaPor"); }
        }
   
        public static string OfertasTrabajo
        {
            get { return GetString("OfertasTrabajo"); }
        }
   
        public static string OfertasTrabajoDescripcion
        {
            get { return GetString("OfertasTrabajoDescripcion"); }
        }
   
        public static string OfertaTrabajoAceptada
        {
            get { return GetString("OfertaTrabajoAceptada"); }
        }
   
        public static string OfertaTrabajoAceptadaDescripcion
        {
            get { return GetString("OfertaTrabajoAceptadaDescripcion"); }
        }
   
        public static string OlvidarContrasenna
        {
            get { return GetString("OlvidarContrasenna"); }
        }
   
        public static string OlvidoSuContrasennaPregunta
        {
            get { return GetString("OlvidoSuContrasennaPregunta"); }
        }
   
        public static string OpcionAgregarPresupuesto
        {
            get { return GetString("OpcionAgregarPresupuesto"); }
        }
   
        public static string PaisDeNacimiento
        {
            get { return GetString("PaisDeNacimiento"); }
        }
   
        public static string PanelControl
        {
            get { return GetString("PanelControl"); }
        }
   
        public static string PanelControlDescripcion
        {
            get { return GetString("PanelControlDescripcion"); }
        }
   
        public static string Pasaporte
        {
            get { return GetString("Pasaporte"); }
        }
   
        public static string Perfil
        {
            get { return GetString("Perfil"); }
        }
   
        public static string PerfilAdministrador
        {
            get { return GetString("PerfilAdministrador"); }
        }
   
        public static string PorcentajeComisionPorTrabajo
        {
            get { return GetString("PorcentajeComisionPorTrabajo"); }
        }
   
        public static string Precio
        {
            get { return GetString("Precio"); }
        }
   
        public static string PrecioCancelacion
        {
            get { return GetString("PrecioCancelacion"); }
        }
   
        public static string Presupuesto
        {
            get { return GetString("Presupuesto"); }
        }
   
        public static string PrimerApellido
        {
            get { return GetString("PrimerApellido"); }
        }
   
        public static string Productos
        {
            get { return GetString("Productos"); }
        }
   
        public static string PromocioneSuTrabajo
        {
            get { return GetString("PromocioneSuTrabajo"); }
        }
   
        public static string PromocioneSuTrabajoDescripcion
        {
            get { return GetString("PromocioneSuTrabajoDescripcion"); }
        }
   
        public static string Provincia
        {
            get { return GetString("Provincia"); }
        }
   
        public static string RazonSocial
        {
            get { return GetString("RazonSocial"); }
        }
   
        public static string RealizarPagoSolicitud
        {
            get { return GetString("RealizarPagoSolicitud"); }
        }
   
        public static string RealizarPagoSolicitudDescripcion
        {
            get { return GetString("RealizarPagoSolicitudDescripcion"); }
        }
   
        public static string RealizarPagoSolicitudPaypal
        {
            get { return GetString("RealizarPagoSolicitudPaypal"); }
        }
   
        public static string Rechazar
        {
            get { return GetString("Rechazar"); }
        }
   
        public static string RechazarOfertaTrabajo
        {
            get { return GetString("RechazarOfertaTrabajo"); }
        }
   
        public static string RechazarOfertaTrabajoDescripcion
        {
            get { return GetString("RechazarOfertaTrabajoDescripcion"); }
        }
   
        public static string RecibaSusGanancias
        {
            get { return GetString("RecibaSusGanancias"); }
        }
   
        public static string RecibaSusGananciasDescripcion
        {
            get { return GetString("RecibaSusGananciasDescripcion"); }
        }
   
        public static string RegistrarAdministrador
        {
            get { return GetString("RegistrarAdministrador"); }
        }
   
        public static string RegistrarCliente
        {
            get { return GetString("RegistrarCliente"); }
        }
   
        public static string RegistrarOferenteFisico
        {
            get { return GetString("RegistrarOferenteFisico"); }
        }
   
        public static string RegistrarOferenteJuridico
        {
            get { return GetString("RegistrarOferenteJuridico"); }
        }
   
        public static string RegistrarTrabajador
        {
            get { return GetString("RegistrarTrabajador"); }
        }
   
        public static string RegistreseAhora
        {
            get { return GetString("RegistreseAhora"); }
        }
   
        public static string RegistreseSinNingunCostoAdicional
        {
            get { return GetString("RegistreseSinNingunCostoAdicional"); }
        }
   
        public static string RegresarListaOfertas
        {
            get { return GetString("RegresarListaOfertas"); }
        }
   
        public static string Residente
        {
            get { return GetString("Residente"); }
        }
   
        public static string Rol
        {
            get { return GetString("Rol"); }
        }
   
        public static string RolDescripcion
        {
            get { return GetString("RolDescripcion"); }
        }
   
        public static string Roles
        {
            get { return GetString("Roles"); }
        }
   
        public static string Saludo
        {
            get { return GetString("Saludo"); }
        }
   
        public static string SeaUnMaster
        {
            get { return GetString("SeaUnMaster"); }
        }
   
        public static string SegundoApellido
        {
            get { return GetString("SegundoApellido"); }
        }
   
        public static string Seguridad
        {
            get { return GetString("Seguridad"); }
        }
   
        public static string SeguridadDescripcion
        {
            get { return GetString("SeguridadDescripcion"); }
        }
   
        public static string SeleccioneUnaOpcion
        {
            get { return GetString("SeleccioneUnaOpcion"); }
        }
   
        public static string Sistema
        {
            get { return GetString("Sistema"); }
        }
   
        public static string SolicitarCodigoQR
        {
            get { return GetString("SolicitarCodigoQR"); }
        }
   
        public static string Solicitudes
        {
            get { return GetString("Solicitudes"); }
        }
   
        public static string SolicitudesActivas
        {
            get { return GetString("SolicitudesActivas"); }
        }
   
        public static string SolicitudesActivasDescripcion
        {
            get { return GetString("SolicitudesActivasDescripcion"); }
        }
   
        public static string SolicitudesCompletas
        {
            get { return GetString("SolicitudesCompletas"); }
        }
   
        public static string SolicitudesCompletasDescripcion
        {
            get { return GetString("SolicitudesCompletasDescripcion"); }
        }
   
        public static string SolicitudesPendientesAdjudicar
        {
            get { return GetString("SolicitudesPendientesAdjudicar"); }
        }
   
        public static string SolicitudesPendientesAdjudicarDescripcion
        {
            get { return GetString("SolicitudesPendientesAdjudicarDescripcion"); }
        }
   
        public static string SolicitudesPendientesCalificar
        {
            get { return GetString("SolicitudesPendientesCalificar"); }
        }
   
        public static string SolicitudesPendientesCalificarDescripcion
        {
            get { return GetString("SolicitudesPendientesCalificarDescripcion"); }
        }
   
        public static string SolicitudesPorIniciar
        {
            get { return GetString("SolicitudesPorIniciar"); }
        }
   
        public static string SolicitudesTrabajo
        {
            get { return GetString("SolicitudesTrabajo"); }
        }
   
        public static string SolicitudTrabajoEnviada
        {
            get { return GetString("SolicitudTrabajoEnviada"); }
        }
   
        public static string SolicitudTrabajoEnviadaDescripcion
        {
            get { return GetString("SolicitudTrabajoEnviadaDescripcion"); }
        }
   
        public static string SolicitudTrabajoFinalizada
        {
            get { return GetString("SolicitudTrabajoFinalizada"); }
        }
   
        public static string SolicitudTrabajoFinalizadaDescripcion
        {
            get { return GetString("SolicitudTrabajoFinalizadaDescripcion"); }
        }
   
        public static string SolicitudTrabajoIniciada
        {
            get { return GetString("SolicitudTrabajoIniciada"); }
        }
   
        public static string SolicitudTrabajoIniciadaDescripcion
        {
            get { return GetString("SolicitudTrabajoIniciadaDescripcion"); }
        }
   
        public static string SubirDocumento
        {
            get { return GetString("SubirDocumento"); }
        }
   
        public static string SubirFotografia
        {
            get { return GetString("SubirFotografia"); }
        }
   
        public static string Telefono
        {
            get { return GetString("Telefono"); }
        }
   
        public static string TerminosServicio
        {
            get { return GetString("TerminosServicio"); }
        }
   
        public static string TieneEmpresa
        {
            get { return GetString("TieneEmpresa"); }
        }
   
        public static string Tipo
        {
            get { return GetString("Tipo"); }
        }
   
        public static string TipoPago
        {
            get { return GetString("TipoPago"); }
        }
   
        public static string TiposTrabajo
        {
            get { return GetString("TiposTrabajo"); }
        }
   
        public static string Titulo
        {
            get { return GetString("Titulo"); }
        }
   
        public static string Total
        {
            get { return GetString("Total"); }
        }
   
        public static string TotalDolares
        {
            get { return GetString("TotalDolares"); }
        }
   
        public static string Trabajadores
        {
            get { return GetString("Trabajadores"); }
        }
   
        public static string TrabajeConExpertos
        {
            get { return GetString("TrabajeConExpertos"); }
        }
   
        public static string Trabajos
        {
            get { return GetString("Trabajos"); }
        }
   
        public static string URL
        {
            get { return GetString("URL"); }
        }
   
        public static string Usuario
        {
            get { return GetString("Usuario"); }
        }
   
        public static string Usuarios
        {
            get { return GetString("Usuarios"); }
        }
   
        public static string VerboHTTP
        {
            get { return GetString("VerboHTTP"); }
        }
   
        public static string VolverIntentar
        {
            get { return GetString("VolverIntentar"); }
        }
    }
}
